#!/usr/bin/env python3
# ============================================================
#  WiFi/MQTT distributed irrigation system
#  Page 1: Manual Control | Page 2: Weekly Schedule
#  v2.0 - Field deployment
# ============================================================

from flask import Flask, render_template_string, request, jsonify
import datetime, time, threading, json, os, logging, signal, sys
from zoneinfo import ZoneInfo

# ============================================================
# 0. CONFIGURATION — loaded from config.json (generated by configure.sh)
# ============================================================
_CONFIG_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.json")
_cfg = {}
if os.path.exists(_CONFIG_FILE):
    with open(_CONFIG_FILE) as _f:
        _cfg = json.load(_f)

GARDEN_NAME   = _cfg.get("garden_name",   "Irrigation System")
TIMEZONE      = _cfg.get("timezone",      "UTC")
PI_USER       = _cfg.get("pi_username",   "pi")

TZ = ZoneInfo(TIMEZONE)

def now():
    return datetime.datetime.now(TZ)

# ============================================================
# 1. LOGGING
# ============================================================
LOG_DIR  = _cfg.get("log_dir",  os.path.join(os.path.expanduser(f"~{PI_USER}"), "irrigation", "logs"))
LOG_FILE = os.path.join(LOG_DIR, "watering.log")
os.makedirs(LOG_DIR, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.FileHandler(LOG_FILE, encoding="utf-8"),
        logging.StreamHandler(sys.stdout)
    ]
)
log = logging.getLogger("irrigation")

try:
    import paho.mqtt.client as mqtt
    MQTT_AVAILABLE = True
except ImportError:
    MQTT_AVAILABLE = False
    log.warning("paho-mqtt not installed! pip install paho-mqtt")

app = Flask(__name__)

MQTT_BROKER    = "localhost"   # Mosquitto runs locally on the Pi
MQTT_PORT      = 1883
SCHEDULE_FILE  = _cfg.get("schedule_file", os.path.join(os.path.expanduser(f"~{PI_USER}"), "irrigation", "schedule.json"))

# Timing constants
BREAKER_OPEN_DELAYS = [10, 4, 4]
BREAKER_CLOSE_DELAY  = 3
VALVE_OPEN_DELAY       = 6
VALVE_CLOSE_DELAY     = 6
SAFE_SHUTDOWN_DELAY          = 10

# ESP heartbeat timeout — mark offline if not seen for 90 seconds
ESP_TIMEOUT_SECONDS = 90

# ============================================================
# 2. SYSTEM STATE
# ============================================================
STATE = {
    "mode": "OFF",
    "pump": {
        "active": False,
        "sigorta": [False, False, False]
    },
    "city_water": {
        "active": False,
    },
    "valves": {
        str(i): {
            "active":   False,
            "closing":  False,
            "end_time": None,
            "name":     f"Zone {i}"
        } for i in range(1, 16)
    },
    "schedule": [],
    "sensors": {
        "temp":        "--",
        "hum":         "--",
        "soil":        "--",
        "last_update": "Waiting..."
    },
    "mqtt_connected": False,
    "esp_status": {
        "esp1_pompa":  "unknown",
        "esp2_valf8":  "unknown",
        "esp3_valf4a": "unknown",
        "esp4_valf4b": "unknown"
    },
    # Last heartbeat timestamp per ESP (for timeout detection)
    "_esp_last_seen": {
        "esp1_pompa":  None,
        "esp2_valf8":  None,
        "esp3_valf4a": None,
        "esp4_valf4b": None
    }
}

# ============================================================
# 3. MQTT MANAGER
# ============================================================
class MQTTManager:
    def __init__(self):
        self.client    = None
        self.connected = False
        if MQTT_AVAILABLE:
            self.setup()

    def setup(self):
        try:
            self.client = mqtt.Client(client_id="pi_server")
            self.client.on_connect    = self.on_connect
            self.client.on_message    = self.on_message
            self.client.on_disconnect = self.on_disconnect
            self.client.connect_async(MQTT_BROKER, MQTT_PORT, 60)
            self.client.loop_start()
            log.info("MQTT Manager started → %s:%d", MQTT_BROKER, MQTT_PORT)
        except Exception as e:
            log.error("MQTT connection error: %s", e)

    def on_connect(self, client, userdata, flags, rc):
        if rc == 0:
            self.connected          = True
            STATE["mqtt_connected"] = True
            log.info("MQTT Broker connected ✅")
            client.subscribe("sulama/+/durum")
            client.subscribe("sulama/+/heartbeat")
            client.subscribe("sulama/sensor/data")
            # Request current state from all ESPs
            client.publish("sulama/tum/komut", json.dumps({"cmd": "DURUM"}))
        else:
            log.error("MQTT connection failed: rc=%d", rc)

    def on_disconnect(self, client, userdata, rc):
        self.connected          = False
        STATE["mqtt_connected"] = False
        log.warning("MQTT connection lost (rc=%d), reconnecting...", rc)

    def on_message(self, client, userdata, msg):
        topic   = msg.topic
        payload = msg.payload.decode("utf-8", errors="replace")
        try:
            data = json.loads(payload)
        except Exception:
            data = payload

        # Sensor data
        if "sensor" in topic and isinstance(data, dict):
            STATE["sensors"]["temp"]        = data.get("temp", "--")
            STATE["sensors"]["hum"]         = data.get("hum", "--")
            STATE["sensors"]["soil"]        = data.get("soil", "--")
            STATE["sensors"]["last_update"] = now().strftime("%H:%M:%S")

        # ESP heartbeat — update last seen time
        # Topic e.g.: "sulama/esp1/heartbeat" → esp_prefix = "esp1"
        for esp_id in STATE["esp_status"]:
            esp_prefix = esp_id.split("_")[0]   # "esp1_pompa" → "esp1"
            if esp_prefix in topic:
                STATE["esp_status"][esp_id]     = "online"
                STATE["_esp_last_seen"][esp_id] = time.time()

    def publish(self, topic, payload):
        msg = json.dumps(payload) if isinstance(payload, dict) else payload
        if self.connected and self.client:
            try:
                self.client.publish(topic, msg, qos=1)
                log.info("MQTT → %s : %s", topic, msg)
                return True
            except Exception as e:
                log.error("MQTT publish error: %s", e)
        else:
            log.warning("[MQTT NOT CONNECTED] → %s : %s", topic, msg)
        return False

mqtt_mgr = MQTTManager()

# ============================================================
# 4. ESP TIMEOUT CHECK (background thread)
# ============================================================
def esp_timeout_thread():
    """Mark ESPs offline if no heartbeat for 90 seconds"""
    while True:
        try:
            for esp_id, last in STATE["_esp_last_seen"].items():
                if last is None:
                    continue
                elapsed = time.time() - last
                if elapsed > ESP_TIMEOUT_SECONDS:
                    if STATE["esp_status"][esp_id] == "online":
                        log.warning("%s offline (%.0f s since last heartbeat)", esp_id, elapsed)
                    STATE["esp_status"][esp_id] = "offline"
        except Exception as e:
            log.error("ESP timeout check error: %s", e)
        time.sleep(15)

threading.Thread(target=esp_timeout_thread, daemon=True).start()

# ============================================================
# 5. PUMP & VALVE CONTROL FUNCTIONS
# ============================================================
def pump_start():
    if STATE["city_water"]["active"]:
        log.warning("SAFETY: Cannot start pump while city water is active!")
        return
    log.info("Pump starting (breaker sequence: 1→2→3)...")
    for i in range(3):
        STATE["pump"]["sigorta"][i] = True
        mqtt_mgr.publish("sulama/esp1/komut", {"cmd": "SIGORTA_AC", "no": i + 1})
        log.info("Breaker %d on, waiting %ds...", i + 1, BREAKER_OPEN_DELAYS[i])
        time.sleep(BREAKER_OPEN_DELAYS[i])
    STATE["pump"]["active"] = True
    STATE["mode"]           = "PUMP"
    log.info("Pump ACTIVE ✅")

def pump_stop():
    log.info("Pump stopping (reverse sequence: 3→2→1)...")
    STATE["pump"]["active"] = False
    mqtt_mgr.publish("sulama/esp1/komut", {"cmd": "POMPA_KAPAT"})
    time.sleep(1)
    for i in [2, 1, 0]:
        STATE["pump"]["sigorta"][i] = False
        mqtt_mgr.publish("sulama/esp1/komut", {"cmd": "SIGORTA_KAPAT", "no": i + 1})
        log.info("Breaker %d off, waiting %ds...", i + 1, BREAKER_CLOSE_DELAY)
        time.sleep(BREAKER_CLOSE_DELAY)
    STATE["mode"] = "OFF"
    log.info("Pump COMPLETELY OFF ✅")

def valve_open(zone_id):
    esp_topic = _zone_to_esp_topic(zone_id)
    mqtt_mgr.publish(esp_topic, {"cmd": "VALF_AC", "valf": zone_id})
    STATE["valves"][str(zone_id)]["active"]  = True
    STATE["valves"][str(zone_id)]["closing"] = False
    log.info("Valve %d opened", zone_id)

def valve_close(zone_id):
    esp_topic = _zone_to_esp_topic(zone_id)
    mqtt_mgr.publish(esp_topic, {"cmd": "VALF_KAPAT", "valf": zone_id})
    STATE["valves"][str(zone_id)]["active"]   = False
    STATE["valves"][str(zone_id)]["closing"]  = False
    STATE["valves"][str(zone_id)]["end_time"] = None
    log.info("Valve %d closed", zone_id)

def _zone_to_esp_topic(zone_id):
    if zone_id <= 7:
        return "sulama/esp2/komut"
    elif zone_id <= 11:
        return "sulama/esp3/komut"
    else:
        return "sulama/esp4/komut"

def city_water_open():
    if STATE["pump"]["active"]:
        log.warning("SAFETY: Cannot open city water while pump is active!")
        return False
    STATE["city_water"]["active"] = True
    STATE["mode"]             = "CITY"
    mqtt_mgr.publish("sulama/esp2/komut", {"cmd": "VALF_AC", "valf": 8})
    log.info("City water opened ✅")
    return True

def city_water_close():
    STATE["city_water"]["active"] = False
    if STATE["mode"] == "CITY":
        STATE["mode"] = "OFF"
    mqtt_mgr.publish("sulama/esp2/komut", {"cmd": "VALF_KAPAT", "valf": 8})
    log.info("City water closed ✅")

def irrigation_start(zone_id, mod="PUMP"):
    def _thread():
        log.info("Irrigation starting: Zone %d, Mode: %s", zone_id, mod)
        if mod == "PUMP" and STATE["city_water"]["active"]:
            log.warning("SAFETY: Cannot start pump while city water is active!")
            return
        if mod == "CITY" and STATE["pump"]["active"]:
            log.warning("SAFETY: Cannot start city water while pump is active!")
            return
        valve_open(zone_id)
        time.sleep(VALVE_OPEN_DELAY)
        if mod == "PUMP" and not STATE["pump"]["active"]:
            pump_start()
        elif mod == "CITY" and not STATE["city_water"]["active"]:
            city_water_open()

    threading.Thread(target=_thread, daemon=True).start()

def _any_valve_active(exclude_zone=None):
    for i in range(1, 16):
        if exclude_zone and i == exclude_zone:
            continue
        if STATE["valves"][str(i)]["active"]:
            return True
    return False

def irrigation_stop(zone_id, force=False):
    def _thread():
        zone_str = str(zone_id)
        log.info("Irrigation stopping: Zone %d", zone_id)
        STATE["valves"][zone_str]["closing"] = True

        other_valve_active = _any_valve_active(exclude_zone=zone_id)

        if not other_valve_active:
            log.info("Last valve → closing water source first...")
            if STATE["mode"] == "PUMP":
                pump_stop()
            elif STATE["mode"] == "CITY":
                city_water_close()
            log.info("%ds pressure relief...", VALVE_CLOSE_DELAY)
            time.sleep(VALVE_CLOSE_DELAY)
            valve_close(zone_id)
        else:
            log.info("Zone %d closing, other zones continue running", zone_id)
            valve_close(zone_id)

        STATE["valves"][zone_str]["closing"] = False
        log.info("Zone %d fully closed ✅", zone_id)

    threading.Thread(target=_thread, daemon=True).start()

def stop_all():
    def _thread():
        log.warning("EMERGENCY STOP — Shutting down entire system!")
        if STATE["mode"] == "PUMP":
            pump_stop()
        if STATE["city_water"]["active"]:
            city_water_close()
        STATE["mode"] = "OFF"
        time.sleep(2)
        for i in range(1, 16):
            valve_close(i)
        mqtt_mgr.publish("sulama/tum/komut", {"cmd": "TUMU_KAPAT"})
        log.info("Entire system off ✅")

    threading.Thread(target=_thread, daemon=True).start()

# ============================================================
# 6. SAFE SHUTDOWN — on Pi shutdown / restart
# ============================================================
def safe_shutdown(signum=None, frame=None):
    log.warning("System shutting down (signal: %s) — closing all valves...", signum)
    # Run directly without a thread (must finish before process exits)
    if STATE["mode"] == "PUMP":
        pump_stop()
    if STATE["city_water"]["active"]:
        city_water_close()
    time.sleep(2)
    for i in range(1, 16):
        valve_close(i)
    mqtt_mgr.publish("sulama/tum/komut", {"cmd": "TUMU_KAPAT"})
    time.sleep(1)
    log.info("Safe shutdown complete ✅")
    sys.exit(0)

signal.signal(signal.SIGTERM, safe_shutdown)
signal.signal(signal.SIGINT,  safe_shutdown)

# ============================================================
# 7. SCHEDULER & WEEKLY SCHEDULE
# ============================================================
def load_schedule():
    if os.path.exists(SCHEDULE_FILE):
        try:
            with open(SCHEDULE_FILE, "r") as f:
                STATE["schedule"] = json.load(f)
            log.info("%d schedules loaded", len(STATE["schedule"]))
        except Exception as e:
            log.error("Failed to load schedule: %s", e)

def save_schedule():
    try:
        os.makedirs(os.path.dirname(SCHEDULE_FILE), exist_ok=True)
        with open(SCHEDULE_FILE, "w") as f:
            json.dump(STATE["schedule"], f, indent=2, ensure_ascii=False)
        log.info("Schedule saved ✅")
    except Exception as e:
        log.error("Save error: %s", e)

def scheduler_thread():
    fired_this_minute = set()
    while True:
        try:
            current = now()

            # Manual timer check
            for i in range(1, 16):
                v = STATE["valves"][str(i)]
                if v["active"] and v["end_time"] and not v["closing"]:
                    end = datetime.datetime.strptime(
                        v["end_time"], "%Y-%m-%d %H:%M:%S"
                    ).replace(tzinfo=TZ)
                    if current > end:
                        log.info("Timer expired: Zone %d", i)
                        irrigation_stop(i)

            # Weekly schedule check
            if current.second < 2:
                day_map   = {"Mon":0,"Tue":1,"Wed":2,"Thu":3,"Fri":4,"Sat":5,"Sun":6}
                today_idx = current.weekday()
                hhmm      = current.strftime("%H:%M")

                for idx, p in enumerate(STATE["schedule"]):
                    key = f"{idx}_{hhmm}"
                    if key in fired_this_minute:
                        continue
                    if day_map.get(p.get("day"), -1) == today_idx and p.get("time") == hhmm:
                        zone = p["zone"]
                        mod  = p.get("mod", "PUMP")
                        mins = int(p.get("duration", 30))
                        if not STATE["valves"][str(zone)]["active"]:
                            log.info("Auto irrigation: Zone %d (%d min, %s)", zone, mins, mod)
                            end_time = current + datetime.timedelta(minutes=mins)
                            STATE["valves"][str(zone)]["end_time"] = end_time.strftime("%Y-%m-%d %H:%M:%S")
                            irrigation_start(zone, mod)
                            fired_this_minute.add(key)
            else:
                fired_this_minute.clear()

        except Exception as e:
            log.error("Scheduler error: %s", e)
        time.sleep(1)

load_schedule()
threading.Thread(target=scheduler_thread, daemon=True).start()

# ============================================================
# 8. HTML TEMPLATE
# ============================================================
HTML_MAIN = r"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>Reis Garden · Control</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500;700&display=swap" rel="stylesheet">
<style>
/* ─── TOKENS ─────────────────────────────── */
:root {
  --bg:        #080c10;
  --surface:   #0d1520;
  --card:      #111d2e;
  --border:    #1e3048;
  --text:      #d4e4f7;
  --muted:     #4a6580;
  --gold:      #e8a923;
  --gold-glow: rgba(232,169,35,.18);
  --green:     #22d98a;
  --green-glow:rgba(34,217,138,.15);
  --blue:      #3b9eff;
  --blue-glow: rgba(59,158,255,.15);
  --red:       #ff4455;
  --red-glow:  rgba(255,68,85,.15);
  --orange:    #ff8c00;
  --radius:    14px;
  --font-head: 'Bebas Neue', sans-serif;
  --font-body: 'DM Sans', sans-serif;
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: var(--font-body);
  background: var(--bg);
  color: var(--text);
  min-height: 100vh;
  padding-bottom: 30px;
  background-image:
    radial-gradient(ellipse 80% 40% at 50% -20%, rgba(59,158,255,.06), transparent),
    radial-gradient(ellipse 60% 30% at 80% 80%, rgba(34,217,138,.04), transparent);
}

/* ─── HEADER ──────────────────────────── */
.header {
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  padding: 14px 18px 10px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  position: sticky;
  top: 0;
  z-index: 100;
  backdrop-filter: blur(12px);
}
.header-left { display: flex; align-items: baseline; gap: 10px; }
.logo { font-family: var(--font-head); font-size: 28px; letter-spacing: 1px; color: var(--gold);
  text-shadow: 0 0 20px var(--gold-glow); line-height: 1; }
.logo-sub { font-size: 11px; color: var(--muted); font-weight: 500; letter-spacing: .5px; }
.header-right { display: flex; align-items: center; gap: 8px; flex-shrink: 0; }
.mqtt-dot {
  width: 8px; height: 8px; border-radius: 50%;
  background: var(--red); transition: background .4s;
}
.mqtt-dot.live { background: var(--green); box-shadow: 0 0 8px var(--green); }
.clock { font-family: var(--font-head); font-size: 20px; color: var(--gold); letter-spacing: 1px; }

/* ─── NAV TABS ────────────────────────── */
.tabs {
  display: flex;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
}
.tab {
  flex: 1; text-align: center; padding: 12px 8px;
  font-size: 13px; font-weight: 600; color: var(--muted);
  text-decoration: none; letter-spacing: .3px;
  border-bottom: 3px solid transparent; transition: all .2s; cursor: pointer;
}
.tab.active { color: var(--gold); border-bottom-color: var(--gold); }

/* ─── SENSOR BAR ──────────────────────── */
.sensor-bar {
  display: flex; justify-content: space-around;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  padding: 10px 0;
}
.s-item { text-align: center; }
.s-val { display: block; font-family: var(--font-head); font-size: 22px; line-height: 1; }
.s-lbl { font-size: 10px; color: var(--muted); text-transform: uppercase; letter-spacing: .5px; }
.s-time { text-align: center; font-size: 10px; color: var(--muted); padding: 4px 0;
  background: var(--surface); border-bottom: 1px solid var(--border); }

/* ─── SECTIONS ────────────────────────── */
.section { padding: 14px 14px 0; }
.section-title {
  font-family: var(--font-head); font-size: 16px; letter-spacing: 1px;
  color: var(--muted); margin-bottom: 10px; display: flex; align-items: center; gap: 8px;
}
.section-title::after {
  content: ''; flex: 1; height: 1px; background: var(--border);
}

/* ─── MODE BUTTONS ────────────────────── */
.mode-row { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 10px; }
.mode-btn {
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  padding: 18px 12px; border-radius: var(--radius);
  border: 2px solid var(--border); background: var(--card);
  color: var(--muted); font-weight: 700; font-size: 14px; cursor: pointer;
  transition: all .2s; gap: 6px; position: relative; overflow: hidden;
}
.mode-btn .icon { font-size: 28px; }
.mode-btn.pump-btn { border-color: #1e5c3c; }
.mode-btn.pump-btn.active {
  background: var(--green-glow); border-color: var(--green); color: var(--green);
  box-shadow: 0 0 20px var(--green-glow);
}
.mode-btn.city-btn { border-color: #1a3a5c; }
.mode-btn.city-btn.active {
  background: var(--blue-glow); border-color: var(--blue); color: var(--blue);
  box-shadow: 0 0 20px var(--blue-glow);
}

.sigorta-row { display: flex; gap: 5px; margin-top: 4px; }
.sig-dot {
  width: 10px; height: 10px; border-radius: 50%;
  background: var(--border); transition: all .3s;
}
.sig-dot.active { background: var(--green); box-shadow: 0 0 6px var(--green); }

.stop-btn {
  width: 100%; padding: 16px; border-radius: var(--radius);
  border: 2px solid #5c1a22; background: var(--red-glow);
  color: var(--red); font-weight: 800; font-size: 15px;
  cursor: pointer; letter-spacing: .5px; transition: all .2s;
  margin-bottom: 14px;
}
.stop-btn:hover { background: rgba(255,68,85,.25); border-color: var(--red); }

/* ─── ZONE GRID ───────────────────────── */
.zone-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 9px;
  margin-bottom: 4px;
}
.zone-btn {
  aspect-ratio: 1;
  display: flex; flex-direction: column;
  align-items: center; justify-content: center;
  border-radius: 12px; border: 1.5px solid var(--border);
  background: var(--card); cursor: pointer;
  transition: all .2s; position: relative;
  gap: 2px; overflow: hidden;
  -webkit-tap-highlight-color: transparent;
}
.zone-btn .z-group { font-size: 9px; color: var(--muted); text-transform: uppercase; }
.zone-btn .z-num { font-family: var(--font-head); font-size: 22px; color: var(--text); line-height: 1; }
.zone-btn .z-timer { font-size: 9px; color: var(--muted); }

.zone-btn.active { background: var(--green-glow); border-color: var(--green); }
.zone-btn.active .z-num { color: var(--green); }
.zone-btn.active .z-timer { color: var(--green); }

.zone-btn.closing {
  background: rgba(255,140,0,.1); border-color: var(--orange);
  animation: pulse-warn 1s ease-in-out infinite;
}
.zone-btn.closing .z-num { color: var(--orange); }
@keyframes pulse-warn { 0%,100%{opacity:1} 50%{opacity:.55} }

.badge {
  position: absolute; top: 4px; right: 4px;
  font-size: 8px; font-weight: 700; padding: 2px 5px;
  border-radius: 4px; text-transform: uppercase; letter-spacing: .3px;
}
.badge-open    { background: var(--green); color: #000; }
.badge-closing { background: var(--orange); color: #000; }

/* ─── ESP STATUS BAR ─────────────────── */
.esp-bar {
  display: flex; justify-content: space-around;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  padding: 8px 0;
}
.esp-item { text-align: center; font-size: 10px; color: var(--muted); }
.esp-dot {
  display: inline-block; width: 7px; height: 7px; border-radius: 50%;
  background: var(--red); margin-right: 3px; vertical-align: middle;
}
.esp-dot.online  { background: var(--green);  box-shadow: 0 0 6px var(--green); }
.esp-dot.offline { background: var(--orange); box-shadow: 0 0 6px var(--orange); }

/* ─── TIMER MODAL ─────────────────────── */
.modal-bg {
  display: none; position: fixed; inset: 0; z-index: 200;
  background: rgba(0,0,0,.7); backdrop-filter: blur(6px);
  align-items: center; justify-content: center;
}
.modal-bg.show { display: flex; }
.modal {
  background: var(--card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 24px 20px;
  width: 90%; max-width: 340px; text-align: center;
}
.modal h3 { font-family: var(--font-head); font-size: 20px; color: var(--gold); margin-bottom: 14px; }
.modal-input {
  width: 100%; padding: 12px; border-radius: 10px;
  border: 1px solid var(--border); background: var(--surface);
  color: var(--text); font-size: 18px; text-align: center;
  font-family: var(--font-head); letter-spacing: 2px;
  margin-bottom: 14px;
}
.modal-btns { display: flex; gap: 10px; }
.modal-btn {
  flex: 1; padding: 12px; border-radius: 10px; border: none;
  font-weight: 700; font-size: 14px; cursor: pointer;
}
.modal-btn.ok { background: var(--green); color: #000; }
.modal-btn.cancel { background: var(--border); color: var(--text); }

/* ─── SCHEDULE PAGE ──────────────────── */
.sch-list { display: flex; flex-direction: column; gap: 8px; }
.sch-card {
  background: var(--card); border: 1px solid var(--border);
  border-radius: 10px; padding: 12px 14px;
  display: flex; align-items: center; justify-content: space-between;
}
.sch-info { font-size: 13px; }
.sch-day { font-weight: 700; color: var(--gold); }
.sch-time { color: var(--blue); font-family: var(--font-head); font-size: 16px; }
.sch-del {
  background: none; border: 1px solid var(--red); color: var(--red);
  border-radius: 8px; padding: 6px 10px; cursor: pointer; font-size: 12px;
}
.sch-form {
  background: var(--card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 16px; margin-top: 10px;
}
.sch-form select, .sch-form input {
  width: 100%; padding: 10px; margin-bottom: 10px;
  border-radius: 8px; border: 1px solid var(--border);
  background: var(--surface); color: var(--text); font-size: 14px;
}
.sch-form button {
  width: 100%; padding: 12px; border-radius: 10px; border: none;
  background: var(--gold); color: #000; font-weight: 700; font-size: 14px;
  cursor: pointer;
}

.hidden { display: none; }
</style>
</head>
<body>

<!-- HEADER -->
<div class="header">
  <div class="header-left">
    <span class="logo">REIS GARDEN</span>
    <span class="logo-sub">IRRIGATION</span>
  </div>
  <div class="header-right">
    <span class="mqtt-dot {{ 'live' if mqtt_ok else '' }}"></span>
    <span class="clock" id="clock">--:--</span>
  </div>
</div>

<!-- NAV -->
<div class="tabs">
  <a class="tab active" id="tab-ctrl" onclick="showPage('ctrl')">⚙ CONTROL</a>
  <a class="tab" id="tab-sch" onclick="showPage('sch')">📅 SCHEDULE</a>
</div>

<!-- SENSOR BAR -->
<div class="sensor-bar">
  <div class="s-item"><span class="s-val" style="color:var(--red)" id="s-temp">{{ s.temp }}°</span><span class="s-lbl">Temp</span></div>
  <div class="s-item"><span class="s-val" style="color:var(--blue)" id="s-hum">{{ s.hum }}%</span><span class="s-lbl">Humidity</span></div>
  <div class="s-item"><span class="s-val" style="color:var(--green)" id="s-soil">{{ s.soil }}%</span><span class="s-lbl">Soil</span></div>
</div>
<div class="s-time" id="s-time">Last updated: {{ s.last_update }}</div>

<!-- ESP STATUS -->
<div class="esp-bar" id="esp-bar">
  {% for key, val in esp.items() %}
  <div class="esp-item">
    <span class="esp-dot {{ 'online' if val == 'online' else ('offline' if val == 'offline' else '') }}" data-esp="{{ key }}"></span>
    {{ key.split('_')[0]|upper }}
  </div>
  {% endfor %}
</div>

<!-- PAGE 1: KONTROL -->
<div id="page-ctrl">
  <div class="section">
    <div class="section-title">WATER SOURCE</div>
    <div class="mode-row">
      <button class="mode-btn pump-btn" id="btn-pump" onclick="setMode('PUMP')">
        <span class="icon">⛽</span> POMPA
        <div class="sigorta-row" id="sigorta-row">
          <span class="sig-dot" data-sig="0"></span>
          <span class="sig-dot" data-sig="1"></span>
          <span class="sig-dot" data-sig="2"></span>
        </div>
      </button>
      <button class="mode-btn city-btn" id="btn-city" onclick="setMode('CITY')">
        <span class="icon">🏙</span> CITY WATER
      </button>
    </div>
    <button class="stop-btn" onclick="stopAll()">🛑 STOP ALL</button>
  </div>

  <div class="section">
    <div class="section-title">ZONES</div>
    <div class="zone-grid" id="zone-grid">
      {% for i in range(1, 16) %}
      {% set v = valves[i|string] %}
      <button class="zone-btn" id="zone-{{ i }}" onclick="zoneClick({{ i }})">
        {% if i <= 7 %}<span class="z-group">ESP2</span>
        {% elif i <= 11 %}<span class="z-group">ESP3</span>
        {% else %}<span class="z-group">ESP4</span>{% endif %}
        <span class="z-num">{{ i }}</span>
        <span class="z-timer">{{ v.name }}</span>
      </button>
      {% endfor %}
    </div>
  </div>
</div>

<!-- PAGE 2: PROGRAM -->
<div id="page-sch" class="hidden">
  <div class="section">
    <div class="section-title">WEEKLY SCHEDULE</div>
    <div class="sch-list" id="sch-list"></div>
    <div class="sch-form">
      <select id="sch-day">
        <option value="Mon">Monday</option><option value="Tue">Tuesday</option>
        <option value="Wed">Wednesday</option><option value="Thu">Thursday</option>
        <option value="Fri">Friday</option><option value="Sat">Saturday</option>
        <option value="Sun">Sunday</option>
      </select>
      <input type="time" id="sch-time" value="06:00">
      <select id="sch-zone">
        {% for i in range(1, 16) %}
        <option value="{{ i }}">{{ valves[i|string].name }} ({{ i }})</option>
        {% endfor %}
      </select>
      <select id="sch-mod">
        <option value="PUMP">Pump</option>
        <option value="CITY">City Water</option>
      </select>
      <input type="number" id="sch-dur" value="30" min="1" max="240" placeholder="Duration (min)">
      <button onclick="addSchedule()">➕ ADD SCHEDULE</button>
    </div>
  </div>
</div>

<!-- TIMER MODAL -->
<div class="modal-bg" id="modal">
  <div class="modal">
    <h3 id="modal-title">Zone 1</h3>
    <p style="color:var(--muted); font-size:13px; margin-bottom:12px;">Duration (minutes)</p>
    <input class="modal-input" id="modal-mins" type="number" value="30" min="1" max="240">
    <div class="modal-btns">
      <button class="modal-btn cancel" onclick="closeModal()">Cancel</button>
      <button class="modal-btn ok" onclick="confirmZone()">Start</button>
    </div>
  </div>
</div>

<script>
let selectedZone = null;
let currentState = null;

function updateClock() {
  const now = new Date();
  document.getElementById('clock').textContent =
    now.toLocaleTimeString('en-US', {hour:'2-digit', minute:'2-digit', second:'2-digit', timeZone:'{{ timezone }}'});
}
setInterval(updateClock, 1000);
updateClock();

function showPage(p) {
  document.getElementById('page-ctrl').classList.toggle('hidden', p !== 'ctrl');
  document.getElementById('page-sch').classList.toggle('hidden', p !== 'sch');
  document.getElementById('tab-ctrl').classList.toggle('active', p === 'ctrl');
  document.getElementById('tab-sch').classList.toggle('active', p === 'sch');
  if (p === 'sch') loadSchedule();
}

function api(url, data) {
  return fetch(url, {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify(data)
  }).then(r => r.json()).then(r => {
    setTimeout(pollState, 200);
    setTimeout(pollState, 800);
    setTimeout(pollState, 2000);
    setTimeout(pollState, 4000);
    return r;
  });
}

function pollState() {
  fetch('/api/state').then(r => r.json()).then(applyState).catch(() => {});
}

function applyState(data) {
  currentState = data;

  document.getElementById('btn-pump').classList.toggle('active', data.mode === 'PUMP');
  document.getElementById('btn-city').classList.toggle('active', data.mode === 'CITY');

  data.pump.sigorta.forEach((on, i) => {
    const dot = document.querySelector(`[data-sig="${i}"]`);
    if (dot) dot.classList.toggle('active', on);
  });

  const mqttDot = document.querySelector('.mqtt-dot');
  if (mqttDot) mqttDot.classList.toggle('live', data.mqtt);

  document.getElementById('s-temp').textContent  = data.sensors.temp + '°';
  document.getElementById('s-hum').textContent   = data.sensors.hum + '%';
  document.getElementById('s-soil').textContent  = data.sensors.soil + '%';
  document.getElementById('s-time').textContent  = 'Last updated: ' + data.sensors.last_update;

  // ESP dots — online / offline / unknown
  Object.entries(data.esp).forEach(([key, val]) => {
    const dot = document.querySelector(`[data-esp="${key}"]`);
    if (!dot) return;
    dot.classList.remove('online', 'offline');
    if (val === 'online')  dot.classList.add('online');
    if (val === 'offline') dot.classList.add('offline');
  });

  for (let i = 1; i <= 15; i++) {
    const btn = document.getElementById('zone-' + i);
    if (!btn) continue;
    const v = data.valves[String(i)];
    if (!v) continue;

    btn.classList.toggle('active',  v.active);
    btn.classList.toggle('closing', v.closing);

    let badge = btn.querySelector('.badge');
    if (v.active) {
      if (!badge) { badge = document.createElement('span'); btn.insertBefore(badge, btn.firstChild); }
      badge.className = 'badge badge-open';
      badge.textContent = 'OPEN';
    } else if (v.closing) {
      if (!badge) { badge = document.createElement('span'); btn.insertBefore(badge, btn.firstChild); }
      badge.className = 'badge badge-closing';
      badge.textContent = 'CLOSNG';
    } else {
      if (badge) badge.remove();
    }

    const timer = btn.querySelector('.z-timer');
    if (timer && v.end_time && v.active) {
      const end  = new Date(v.end_time.replace(' ', 'T'));
      const diff = Math.max(0, Math.floor((end - new Date()) / 1000));
      timer.textContent = Math.floor(diff/60) + ':' + String(diff%60).padStart(2,'0');
      timer.style.color = 'var(--green)';
    } else if (timer) {
      timer.textContent = v.name;
      timer.style.color = '';
    }
  }
}

setInterval(pollState, 1000);
pollState();

function setMode(m) {
  const mode = currentState ? currentState.mode : '';
  if ((m === 'PUMP' && mode === 'PUMP') || (m === 'CITY' && mode === 'CITY')) {
    api('/api/mode', {mode: 'OFF'}); return;
  }
  if (m === 'PUMP' && mode === 'CITY') {
    if (!confirm('City water is on! It will be turned off before pump starts. Continue?')) return;
  }
  if (m === 'CITY' && mode === 'PUMP') {
    if (!confirm('Pump is on! It will be turned off before city water starts. Continue?')) return;
  }
  api('/api/mode', {mode: m});
}

function stopAll() {
  if (confirm('Are you sure you want to stop the entire system?')) {
    api('/api/stop_all', {});
  }
}

function zoneClick(z) {
  if (!currentState) return;
  const v = currentState.valves[String(z)];
  if (!v) return;
  if (v.active || v.closing) { api('/api/valve', {zone: z, action: 'stop'}); return; }
  selectedZone = z;
  document.getElementById('modal-title').textContent = v.name + ' (' + z + ')';
  document.getElementById('modal-mins').value = 30;
  document.getElementById('modal').classList.add('show');
}

function closeModal() {
  document.getElementById('modal').classList.remove('show');
  selectedZone = null;
}

function confirmZone() {
  const mins = parseInt(document.getElementById('modal-mins').value) || 30;
  api('/api/valve', {zone: selectedZone, action: 'start', duration: mins});
  closeModal();
}

function loadSchedule() {
  fetch('/api/schedule').then(r => r.json()).then(data => {
    const list = document.getElementById('sch-list');
    const dayNames = {Mon:'Mon', Tue:'Tue', Wed:'Wed', Thu:'Thu', Fri:'Fri', Sat:'Sat', Sun:'Sun'};
    if (data.schedule.length === 0) {
      list.innerHTML = '<p style="color:var(--muted);text-align:center;padding:20px;">No schedules yet</p>';
      return;
    }
    list.innerHTML = data.schedule.map((s, i) => `
      <div class="sch-card">
        <div class="sch-info">
          <span class="sch-day">${dayNames[s.day] || s.day}</span>
          <span class="sch-time">${s.time}</span>
          · Zone ${s.zone} · ${s.duration}min · ${s.mod || 'PUMP'}
        </div>
        <button class="sch-del" onclick="delSchedule(${i})">✕</button>
      </div>
    `).join('');
  });
}

function addSchedule() {
  const data = {
    day:      document.getElementById('sch-day').value,
    time:     document.getElementById('sch-time').value,
    zone:     parseInt(document.getElementById('sch-zone').value),
    mod:      document.getElementById('sch-mod').value,
    duration: parseInt(document.getElementById('sch-dur').value) || 30
  };
  api('/api/schedule/add', data).then(() => loadSchedule());
}

function delSchedule(idx) {
  api('/api/schedule/delete', {index: idx}).then(() => loadSchedule());
}
</script>
</body>
</html>
"""

# ============================================================
# 9. FLASK ROUTES
# ============================================================

@app.route("/")
def index():
    return render_template_string(
        HTML_MAIN,
        mode     = STATE["mode"],
        sig      = STATE["pump"]["sigorta"],
        valves   = STATE["valves"],
        s        = STATE["sensors"],
        esp      = STATE["esp_status"],
        mqtt_ok  = STATE["mqtt_connected"],
        timezone = TIMEZONE
    )

@app.route("/api/state")
def api_state():
    return jsonify({
        "mode":    STATE["mode"],
        "pump":    STATE["pump"],
        "city_water": STATE["city_water"],
        "valves":  STATE["valves"],
        "sensors": STATE["sensors"],
        "esp":     STATE["esp_status"],
        "mqtt":    STATE["mqtt_connected"]
    })

@app.route("/api/mode", methods=["POST"])
def api_mode():
    data = request.get_json(force=True)
    mode = data.get("mode", "OFF")
    if mode == "PUMP":
        if STATE["city_water"]["active"]:
            city_water_close()
            time.sleep(VALVE_CLOSE_DELAY)
        threading.Thread(target=pump_start, daemon=True).start()
    elif mode == "CITY":
        if STATE["pump"]["active"]:
            pump_stop()
            time.sleep(VALVE_CLOSE_DELAY)
        city_water_open()
    else:
        stop_all()
    return jsonify({"ok": True})

@app.route("/api/valve", methods=["POST"])
def api_valve():
    data   = request.get_json(force=True)
    zone   = int(data.get("zone", 0))
    action = data.get("action", "start")
    if zone < 1 or zone > 15:
        return jsonify({"error": "Invalid zone"}), 400
    if action == "start":
        mins     = int(data.get("duration", 30))
        end_time = now() + datetime.timedelta(minutes=mins)
        STATE["valves"][str(zone)]["end_time"] = end_time.strftime("%Y-%m-%d %H:%M:%S")
        irrigation_start(zone, STATE["mode"] if STATE["mode"] != "OFF" else "PUMP")
    else:
        irrigation_stop(zone)
    return jsonify({"ok": True})

@app.route("/api/stop_all", methods=["POST"])
def api_stop_all():
    stop_all()
    return jsonify({"ok": True})

@app.route("/api/schedule")
def api_schedule_list():
    return jsonify({"schedule": STATE["schedule"]})

@app.route("/api/schedule/add", methods=["POST"])
def api_schedule_add():
    data  = request.get_json(force=True)
    entry = {
        "day":      data.get("day", "Mon"),
        "time":     data.get("time", "06:00"),
        "zone":     int(data.get("zone", 1)),
        "mod":      data.get("mod", "PUMP"),
        "duration": int(data.get("duration", 30))
    }
    STATE["schedule"].append(entry)
    save_schedule()
    return jsonify({"ok": True})

@app.route("/api/schedule/delete", methods=["POST"])
def api_schedule_delete():
    data = request.get_json(force=True)
    idx  = int(data.get("index", -1))
    if 0 <= idx < len(STATE["schedule"]):
        STATE["schedule"].pop(idx)
        save_schedule()
    return jsonify({"ok": True})

# ============================================================
# 10. START SERVER
# ============================================================
if __name__ == "__main__":
    log.info("=" * 50)
    log.info("  REIS ORGANIC GARDEN - Irrigation Control Server")
    log.info("  http://0.0.0.0:5000")
    log.info("  Log: %s", LOG_FILE)
    log.info("=" * 50)
    app.run(host="0.0.0.0", port=5000, debug=False)

