#!/usr/bin/env python3
# ============================================================
#  Automated Irrigation System - Pi3 Main Server
#  WiFi/MQTT distributed irrigation system
#  Page 1: Manual Control | Page 2: Weekly Schedule
# ============================================================

from flask import Flask, render_template_string, request, jsonify, redirect
import datetime, time, threading, json, os
from zoneinfo import ZoneInfo

# ============================================================
# 0. CONFIGURATION — loaded from config.json (generated by configure.sh)
# ============================================================
_CONFIG_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.json")
_cfg = {}
if os.path.exists(_CONFIG_FILE):
    with open(_CONFIG_FILE) as _f:
        _cfg = json.load(_f)

GARDEN_NAME = _cfg.get("garden_name", "Irrigation System")
TIMEZONE    = _cfg.get("timezone",    "UTC")
PI_USER     = _cfg.get("pi_username", "pi")

TZ = ZoneInfo(TIMEZONE)

def now():
    """Current time in configured timezone"""
    return datetime.datetime.now(TZ)

# MQTT: pip install paho-mqtt
# Runs in simulation mode without MQTT, activate once MQTT is installed
try:
    import paho.mqtt.client as mqtt
    MQTT_AVAILABLE = True
except ImportError:
    MQTT_AVAILABLE = False

app = Flask(__name__)

MQTT_BROKER = "localhost"   # Pi's own IP
MQTT_PORT   = 1883

SCHEDULE_FILE = _cfg.get("schedule_file", os.path.join(os.path.expanduser(f"~{PI_USER}"), "irrigation", "schedule.json"))

# Pump open/close timing (seconds)
BREAKER_OPEN_DELAYS = [10, 4, 4]   # Open: Breaker1→10s, Breaker2→4s, Breaker3→4s
BREAKER_CLOSE_DELAY  = 3            # Close: 3s between each breaker
VALVE_OPEN_DELAY    = 6    # Before starting pump after valve opens
VALVE_CLOSE_DELAY  = 6    # After stopping pump before valve closes (pressure relief)
SAFE_SHUTDOWN_DELAY       = 10   # General safe shutdown delay

# ============================================================
# 2. SYSTEM STATE
# ============================================================
STATE = {
    "mode": "OFF",          # OFF | PUMP | CITY
    "pump": {
        "active": False,
        "sigorta": [False, False, False]   # 3 breakers
    },
    "city_water": {
        "active": False,     # City water valve state (ESP2 channel 8)
    },
    "valves": {
        # 1-7:   Irrigation valves (ESP2 - channels 1-7)
        # 8-11:  4-ch module A   (ESP3)
        # 12-15: 4-ch module B   (ESP4)
        str(i): {
            "active": False,
            "closing": False,
            "end_time": None,
            "name": f"Zone {i}"
        } for i in range(1, 16)
    },
    "schedule": [],
    "sensors": {
        "temp": "--",
        "hum": "--",
        "soil": "--",
        "last_update": "Waiting..."
    },
    "mqtt_connected": False,
    "esp_status": {
        "esp1_pompa": "unknown",
        "esp2_valf8": "unknown",
        "esp3_valf4a": "unknown",
        "esp4_valf4b": "unknown"
    }
}

# ============================================================
# 3. MQTT MANAGER
# ============================================================
class MQTTManager:
    def __init__(self):
        self.client = None
        self.connected = False
        if MQTT_AVAILABLE:
            self.setup()

    def setup(self):
        try:
            self.client = mqtt.Client(client_id="pi_server")
            self.client.on_connect    = self.on_connect
            self.client.on_message    = self.on_message
            self.client.on_disconnect = self.on_disconnect
            self.client.connect_async(MQTT_BROKER, MQTT_PORT, 60)
            self.client.loop_start()
            print("✅ MQTT Manager started")
        except Exception as e:
            print(f"⚠️ MQTT connection error: {e}")

    def on_connect(self, client, userdata, flags, rc):
        if rc == 0:
            self.connected = True
            STATE["mqtt_connected"] = True
            print("✅ MQTT Broker connected")
            # Listen for status from all ESPs
            client.subscribe("sulama/+/durum")
            client.subscribe("sulama/+/heartbeat")
            client.subscribe("sulama/sensor/data")
        else:
            print(f"❌ MQTT connection failed: rc={rc}")

    def on_disconnect(self, client, userdata, rc):
        self.connected = False
        STATE["mqtt_connected"] = False
        print("⚠️ MQTT connection lost")

    def on_message(self, client, userdata, msg):
        topic = msg.topic
        payload = msg.payload.decode("utf-8")
        try:
            data = json.loads(payload)
        except:
            data = payload

        # Sensor data
        if "sensor" in topic:
            if isinstance(data, dict):
                STATE["sensors"]["temp"]        = data.get("temp", "--")
                STATE["sensors"]["hum"]         = data.get("hum", "--")
                STATE["sensors"]["soil"]        = data.get("soil", "--")
                STATE["sensors"]["last_update"] = now().strftime("%H:%M:%S")

        # ESP heartbeat
        for esp_id in ["esp1_pompa", "esp2_valf8", "esp3_valf4a", "esp4_valf4b"]:
            if esp_id.replace("_", "/") in topic or esp_id in topic:
                STATE["esp_status"][esp_id] = "online"

    def publish(self, topic, payload):
        if self.connected and self.client:
            try:
                msg = json.dumps(payload) if isinstance(payload, dict) else payload
                self.client.publish(topic, msg, qos=1)
                print(f"📤 MQTT → {topic}: {msg}")
                return True
            except Exception as e:
                print(f"❌ MQTT publish error: {e}")
        else:
            # No MQTT — simulate (development mode)
            print(f"[SIM] MQTT → {topic}: {payload}")
        return False

mqtt_mgr = MQTTManager()

# ============================================================
# 4. PUMP & VALVE CONTROL FUNCTIONS
# ============================================================
def pump_start():
    """Breaker sequence: 1→2→3, with 10, 4, 4 second delays"""
    if STATE["city_water"]["active"]:
        print("🚨 SAFETY: Cannot start pump while city water is active!")
        return
    print("🔧 Pump starting (breaker sequence)...")
    for i in range(3):
        STATE["pump"]["sigorta"][i] = True
        mqtt_mgr.publish("sulama/esp1/komut", {"cmd": "SIGORTA_AC", "no": i + 1})
        print(f"⚡ Breaker {i+1} on, waiting {BREAKER_OPEN_DELAYS[i]}s...")
        time.sleep(BREAKER_OPEN_DELAYS[i])
    STATE["pump"]["active"] = True
    STATE["mode"] = "PUMP"
    print("✅ Pump active")

def pump_stop():
    """Stop sequence: 3→2→1 (reverse), 3 seconds each"""
    print("🔧 Pump stopping (reverse breaker sequence)...")
    STATE["pump"]["active"] = False
    mqtt_mgr.publish("sulama/esp1/komut", {"cmd": "POMPA_KAPAT"})
    time.sleep(1)
    for i in [2, 1, 0]:
        STATE["pump"]["sigorta"][i] = False
        mqtt_mgr.publish("sulama/esp1/komut", {"cmd": "SIGORTA_KAPAT", "no": i + 1})
        print(f"⚡ Breaker {i+1} off, waiting {BREAKER_CLOSE_DELAY}s...")
        time.sleep(BREAKER_CLOSE_DELAY)
    STATE["mode"] = "OFF"
    print("✅ Pump completely off")

def valve_open(zone_id):
    """Open valve — send to ESP2, ESP3, or ESP4"""
    esp_topic = _zone_to_esp_topic(zone_id)
    mqtt_mgr.publish(esp_topic, {"cmd": "VALF_AC", "valf": zone_id})
    STATE["valves"][str(zone_id)]["active"] = True
    STATE["valves"][str(zone_id)]["closing"] = False
    print(f"✅ Valve {zone_id} opened")

def valve_close(zone_id):
    """Close valve"""
    esp_topic = _zone_to_esp_topic(zone_id)
    mqtt_mgr.publish(esp_topic, {"cmd": "VALF_KAPAT", "valf": zone_id})
    STATE["valves"][str(zone_id)]["active"] = False
    STATE["valves"][str(zone_id)]["closing"] = False
    STATE["valves"][str(zone_id)]["end_time"] = None
    print(f"✅ Valve {zone_id} closed")

def _zone_to_esp_topic(zone_id):
    if zone_id <= 7:
        return "sulama/esp2/komut"
    elif zone_id <= 11:
        return "sulama/esp3/komut"
    else:
        return "sulama/esp4/komut"

def city_water_open():
    """Open city water valve (ESP2 channel 8) — pump MUST be off"""
    if STATE["pump"]["active"]:
        print("🚨 SAFETY: Cannot open city water while pump is active!")
        return False
    STATE["city_water"]["active"] = True
    STATE["mode"] = "CITY"
    mqtt_mgr.publish("sulama/esp2/komut", {"cmd": "VALF_AC", "valf": 8})
    print("✅ City water opened")
    return True

def city_water_close():
    """Close city water valve"""
    STATE["city_water"]["active"] = False
    if STATE["mode"] == "CITY":
        STATE["mode"] = "OFF"
    mqtt_mgr.publish("sulama/esp2/komut", {"cmd": "VALF_KAPAT", "valf": 8})
    print("✅ City water closed")

def irrigation_start(zone_id, mod="PUMP"):
    """
    Full irrigation start procedure:
    1. Safety check (pump/city water mutual interlock)
    2. Open valve
    3. Wait 6 seconds (water line fills)
    4. Start pump or city water
    """
    def _thread():
        print(f"💧 Irrigation starting: Zone {zone_id}, Mode: {mod}")

        # SAFETY: Mutual interlock
        if mod == "PUMP" and STATE["city_water"]["active"]:
            print("🚨 SAFETY: Cannot start pump while city water is active!")
            return
        if mod == "CITY" and STATE["pump"]["active"]:
            print("🚨 SAFETY: Cannot start city water while pump is active!")
            return

        # Step 1: Open valve
        valve_open(zone_id)
        # Step 2: Water line fills
        time.sleep(VALVE_OPEN_DELAY)
        # Step 3: Pump or city water (only if not already active)
        if mod == "PUMP" and not STATE["pump"]["active"]:
            pump_start()
        elif mod == "CITY" and not STATE["city_water"]["active"]:
            city_water_open()

    threading.Thread(target=_thread, daemon=True).start()

def _any_valve_active(exclude_zone=None):
    """Check if any valve is active (optionally excluding one)"""
    for i in range(1, 16):
        if exclude_zone and i == exclude_zone:
            continue
        if STATE["valves"][str(i)]["active"]:
            return True
    return False

def irrigation_stop(zone_id, force=False):
    """
    Safe stop procedure (CORRECT ORDER):
    - Last valve: 1) Stop pump/city water  2) Wait 6s (pressure relief)  3) Close valve
    - Other valves open: just close this valve, pump keeps running
    """
    def _thread():
        zone_str = str(zone_id)
        print(f"🛑 Irrigation stopping: Zone {zone_id}")
        STATE["valves"][zone_str]["closing"] = True

        # Any other valve open besides this zone?
        other_valve_active = _any_valve_active(exclude_zone=zone_id)

        if not other_valve_active:
            # ── LAST VALVE: close water source first, then valve ──
            print("🔧 Last valve closing → stopping water source first...")
            if STATE["mode"] == "PUMP":
                pump_stop()   # Breaker reverse sequence: 3→2→1
            elif STATE["mode"] == "CITY":
                city_water_close()
            # Let pressurized water drain from pipe
            print(f"⏳ {VALVE_CLOSE_DELAY}s pressure relief...")
            time.sleep(VALVE_CLOSE_DELAY)
            # Now safely close the valve
            valve_close(zone_id)
        else:
            # ── OTHER VALVES OPEN: just close this valve ──
            print(f"ℹ️ Zone {zone_id} closing, pump continues for other zones")
            valve_close(zone_id)

        STATE["valves"][zone_str]["closing"] = False
        print(f"✅ Zone {zone_id} fully closed")

    threading.Thread(target=_thread, daemon=True).start()

def stop_all():
    """Emergency stop — entire system"""
    def _thread():
        print("🚨 EMERGENCY STOP - Shutting down entire system")
        if STATE["mode"] == "PUMP":
            pump_stop()
        if STATE["city_water"]["active"]:
            city_water_close()
        STATE["mode"] = "OFF"
        time.sleep(2)
        for i in range(1, 16):
            valve_close(i)
        mqtt_mgr.publish("sulama/tum/komut", {"cmd": "TUMU_KAPAT"})
        print("✅ Entire system off")

    threading.Thread(target=_thread, daemon=True).start()

# ============================================================
# 5. SCHEDULER & WEEKLY SCHEDULE
# ============================================================
def load_schedule():
    if os.path.exists(SCHEDULE_FILE):
        try:
            with open(SCHEDULE_FILE, "r") as f:
                STATE["schedule"] = json.load(f)
            print(f"✅ {len(STATE['schedule'])} schedules loaded")
        except Exception as e:
            print(f"⚠️ Failed to load schedule: {e}")

def save_schedule():
    try:
        os.makedirs(os.path.dirname(SCHEDULE_FILE), exist_ok=True)
        with open(SCHEDULE_FILE, "w") as f:
            json.dump(STATE["schedule"], f, indent=2, ensure_ascii=False)
        print("💾 Schedule saved")
    except Exception as e:
        print(f"❌ Save error: {e}")

def scheduler_thread():
    fired_this_minute = set()
    while True:
        try:
            current = now()

            # Manual timer check
            for i in range(1, 16):
                v = STATE["valves"][str(i)]
                if v["active"] and v["end_time"] and not v["closing"]:
                    end = datetime.datetime.strptime(v["end_time"], "%Y-%m-%d %H:%M:%S").replace(tzinfo=TZ)
                    if current > end:
                        print(f"⏰ Timer expired: Zone {i}")
                        irrigation_stop(i)

            # Weekly schedule check
            if current.second < 2:
                day_map = {"Mon": 0, "Tue": 1, "Wed": 2, "Thu": 3, "Fri": 4, "Sat": 5, "Sun": 6}
                today_idx = current.weekday()
                hhmm = current.strftime("%H:%M")

                for idx, p in enumerate(STATE["schedule"]):
                    key = f"{idx}_{hhmm}"
                    if key in fired_this_minute:
                        continue
                    if day_map.get(p.get("day"), -1) == today_idx and p.get("time") == hhmm:
                        zone = p["zone"]
                        mod  = p.get("mod", "PUMP")
                        mins = int(p.get("duration", 30))
                        if not STATE["valves"][str(zone)]["active"]:
                            print(f"⏰ Auto irrigation: Zone {zone} ({mins} min)")
                            end_time = current + datetime.timedelta(minutes=mins)
                            STATE["valves"][str(zone)]["end_time"] = end_time.strftime("%Y-%m-%d %H:%M:%S")
                            irrigation_start(zone, mod)
                            fired_this_minute.add(key)
            else:
                fired_this_minute.clear()

        except Exception as e:
            print(f"❌ Scheduler error: {e}")
        time.sleep(1)

load_schedule()
threading.Thread(target=scheduler_thread, daemon=True).start()

# ============================================================
# 6. HTML TEMPLATE
# ============================================================
HTML_MAIN = r"""
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<title>Reis Garden · Control</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500;700&display=swap" rel="stylesheet">
<style>
/* ─── TOKENS ─────────────────────────────── */
:root {
  --bg:        #080c10;
  --surface:   #0d1520;
  --card:      #111d2e;
  --border:    #1e3048;
  --text:      #d4e4f7;
  --muted:     #4a6580;
  --gold:      #e8a923;
  --gold-glow: rgba(232,169,35,.18);
  --green:     #22d98a;
  --green-glow:rgba(34,217,138,.15);
  --blue:      #3b9eff;
  --blue-glow: rgba(59,158,255,.15);
  --red:       #ff4455;
  --red-glow:  rgba(255,68,85,.15);
  --orange:    #ff8c00;
  --radius:    14px;
  --font-head: 'Bebas Neue', sans-serif;
  --font-body: 'DM Sans', sans-serif;
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: var(--font-body);
  background: var(--bg);
  color: var(--text);
  min-height: 100vh;
  padding-bottom: 30px;
  background-image:
    radial-gradient(ellipse 80% 40% at 50% -20%, rgba(59,158,255,.06), transparent),
    radial-gradient(ellipse 60% 30% at 80% 80%, rgba(34,217,138,.04), transparent);
}

/* ─── HEADER ──────────────────────────── */
.header {
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  padding: 14px 18px 10px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  position: sticky;
  top: 0;
  z-index: 100;
  backdrop-filter: blur(12px);
}
.header-left { display: flex; align-items: baseline; gap: 10px; }
.logo { font-family: var(--font-head); font-size: 28px; letter-spacing: 1px; color: var(--gold);
  text-shadow: 0 0 20px var(--gold-glow); line-height: 1; }
.logo-sub { font-size: 11px; color: var(--muted); font-weight: 500; letter-spacing: .5px; }
.header-right { display: flex; align-items: center; gap: 8px; flex-shrink: 0; }
.mqtt-dot {
  width: 8px; height: 8px; border-radius: 50%;
  background: var(--red); transition: background .4s;
}
.mqtt-dot.live { background: var(--green); box-shadow: 0 0 8px var(--green); }
.clock { font-family: var(--font-head); font-size: 20px; color: var(--gold); letter-spacing: 1px; }

/* ─── NAV TABS ────────────────────────── */
.tabs {
  display: flex;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
}
.tab {
  flex: 1; text-align: center; padding: 12px 8px;
  font-size: 13px; font-weight: 600; color: var(--muted);
  text-decoration: none; letter-spacing: .3px;
  border-bottom: 3px solid transparent; transition: all .2s;
}
.tab.active { color: var(--gold); border-bottom-color: var(--gold); }

/* ─── SENSOR BAR ──────────────────────── */
.sensor-bar {
  display: flex; justify-content: space-around;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  padding: 10px 0;
}
.s-item { text-align: center; }
.s-val { display: block; font-family: var(--font-head); font-size: 22px; line-height: 1; }
.s-lbl { font-size: 10px; color: var(--muted); text-transform: uppercase; letter-spacing: .5px; }
.s-time { text-align: center; font-size: 10px; color: var(--muted); padding: 4px 0;
  background: var(--surface); border-bottom: 1px solid var(--border); }

/* ─── SECTIONS ────────────────────────── */
.section { padding: 14px 14px 0; }
.section-title {
  font-family: var(--font-head); font-size: 16px; letter-spacing: 1px;
  color: var(--muted); margin-bottom: 10px; display: flex; align-items: center; gap: 8px;
}
.section-title::after {
  content: ''; flex: 1; height: 1px; background: var(--border);
}

/* ─── MODE BUTTONS ────────────────────── */
.mode-row { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 10px; }
.mode-btn {
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  padding: 18px 12px; border-radius: var(--radius);
  border: 2px solid var(--border); background: var(--card);
  color: var(--muted); font-weight: 700; font-size: 14px; cursor: pointer;
  transition: all .2s; gap: 6px; position: relative; overflow: hidden;
}
.mode-btn .icon { font-size: 28px; }
.mode-btn.pump-btn { border-color: #1e5c3c; }
.mode-btn.pump-btn.active {
  background: var(--green-glow); border-color: var(--green); color: var(--green);
  box-shadow: 0 0 20px var(--green-glow);
}
.mode-btn.city-btn { border-color: #1a3a5c; }
.mode-btn.city-btn.active {
  background: var(--blue-glow); border-color: var(--blue); color: var(--blue);
  box-shadow: 0 0 20px var(--blue-glow);
}

/* Breaker indicator — inside pump button */
.sigorta-row { display: flex; gap: 5px; margin-top: 4px; }
.sig-dot {
  width: 10px; height: 10px; border-radius: 50%;
  background: var(--border); transition: all .3s;
}
.sig-dot.active { background: var(--green); box-shadow: 0 0 6px var(--green); }

.stop-btn {
  width: 100%; padding: 16px; border-radius: var(--radius);
  border: 2px solid #5c1a22; background: var(--red-glow);
  color: var(--red); font-weight: 800; font-size: 15px;
  cursor: pointer; letter-spacing: .5px; transition: all .2s;
  margin-bottom: 14px;
}
.stop-btn:hover { background: rgba(255,68,85,.25); border-color: var(--red); }

/* ─── ZONE GRID ───────────────────────── */
.zone-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 9px;
  margin-bottom: 4px;
}
.zone-btn {
  aspect-ratio: 1;
  display: flex; flex-direction: column;
  align-items: center; justify-content: center;
  border-radius: 12px; border: 1.5px solid var(--border);
  background: var(--card); cursor: pointer;
  transition: all .2s; position: relative;
  gap: 2px; overflow: hidden;
  -webkit-tap-highlight-color: transparent;
}
.zone-btn .z-group { font-size: 9px; color: var(--muted); text-transform: uppercase; }
.zone-btn .z-num { font-family: var(--font-head); font-size: 22px; color: var(--text); line-height: 1; }
.zone-btn .z-timer { font-size: 9px; color: var(--muted); }

.zone-btn.active {
  background: var(--green-glow); border-color: var(--green);
}
.zone-btn.active .z-num { color: var(--green); }
.zone-btn.active .z-timer { color: var(--green); }

.zone-btn.sebeke {
  border-color: #1a3a5c;
}
.zone-btn.sebeke.active {
  background: var(--blue-glow); border-color: var(--blue);
}
.zone-btn.sebeke.active .z-num { color: var(--blue); }

.zone-btn.closing {
  background: rgba(255,140,0,.1); border-color: var(--orange);
  animation: pulse-warn 1s ease-in-out infinite;
}
.zone-btn.closing .z-num { color: var(--orange); }
@keyframes pulse-warn { 0%,100%{opacity:1} 50%{opacity:.55} }

.badge {
  position: absolute; top: 4px; right: 4px;
  font-size: 8px; font-weight: 700; padding: 2px 5px;
  border-radius: 4px; text-transform: uppercase; letter-spacing: .3px;
}
.badge-open    { background: var(--green); color: #000; }
.badge-closing { background: var(--orange); color: #000; }
.badge-seb     { background: var(--blue); color: #000; }

/* ─── TIMER MODAL ─────────────────────── */
.modal-bg {
  display: none; position: fixed; inset: 0; z-index: 200;
  background: rgba(0,0,0,.7); backdrop-filter: blur(6px);
  align-items: center; justify-content: center;
}
.modal-bg.show { display: flex; }
.modal {
  background: var(--card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 24px 20px;
  width: 90%; max-width: 340px; text-align: center;
}
.modal h3 { font-family: var(--font-head); font-size: 20px; color: var(--gold); margin-bottom: 14px; }
.modal-input {
  width: 100%; padding: 12px; border-radius: 10px;
  border: 1px solid var(--border); background: var(--surface);
  color: var(--text); font-size: 18px; text-align: center;
  font-family: var(--font-head); letter-spacing: 2px;
  margin-bottom: 14px;
}
.modal-btns { display: flex; gap: 10px; }
.modal-btn {
  flex: 1; padding: 12px; border-radius: 10px; border: none;
  font-weight: 700; font-size: 14px; cursor: pointer;
}
.modal-btn.ok { background: var(--green); color: #000; }
.modal-btn.cancel { background: var(--border); color: var(--text); }

/* ─── ESP STATUS BAR ─────────────────── */
.esp-bar {
  display: flex; justify-content: space-around;
  background: var(--surface);
  border-bottom: 1px solid var(--border);
  padding: 8px 0;
}
.esp-item { text-align: center; font-size: 10px; color: var(--muted); }
.esp-dot {
  display: inline-block; width: 7px; height: 7px; border-radius: 50%;
  background: var(--red); margin-right: 3px; vertical-align: middle;
}
.esp-dot.online { background: var(--green); box-shadow: 0 0 6px var(--green); }

/* ─── SCHEDULE PAGE ──────────────────── */
.sch-list { display: flex; flex-direction: column; gap: 8px; }
.sch-card {
  background: var(--card); border: 1px solid var(--border);
  border-radius: 10px; padding: 12px 14px;
  display: flex; align-items: center; justify-content: space-between;
}
.sch-info { font-size: 13px; }
.sch-day { font-weight: 700; color: var(--gold); }
.sch-time { color: var(--blue); font-family: var(--font-head); font-size: 16px; }
.sch-del {
  background: none; border: 1px solid var(--red); color: var(--red);
  border-radius: 8px; padding: 6px 10px; cursor: pointer; font-size: 12px;
}
.sch-form {
  background: var(--card); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 16px; margin-top: 10px;
}
.sch-form select, .sch-form input {
  width: 100%; padding: 10px; margin-bottom: 10px;
  border-radius: 8px; border: 1px solid var(--border);
  background: var(--surface); color: var(--text); font-size: 14px;
}
.sch-form button {
  width: 100%; padding: 12px; border-radius: 10px; border: none;
  background: var(--gold); color: #000; font-weight: 700; font-size: 14px;
  cursor: pointer;
}

/* ─── UTILITY ────────────────────────── */
.hidden { display: none; }
</style>
</head>
<body>

<!-- HEADER -->
<div class="header">
  <div class="header-left">
    <span class="logo">REIS GARDEN</span>
    <span class="logo-sub">IRRIGATION</span>
  </div>
  <div class="header-right">
    <span class="mqtt-dot {{ 'live' if mqtt_ok else '' }}"></span>
    <span class="clock" id="clock">--:--</span>
  </div>
</div>

<!-- NAV -->
<div class="tabs">
  <a class="tab active" id="tab-ctrl" onclick="showPage('ctrl')">⚙ CONTROL</a>
  <a class="tab" id="tab-sch" onclick="showPage('sch')">📅 SCHEDULE</a>
</div>

<!-- SENSOR BAR -->
<div class="sensor-bar">
  <div class="s-item"><span class="s-val" style="color:var(--red)">{{ s.temp }}°</span><span class="s-lbl">Temp</span></div>
  <div class="s-item"><span class="s-val" style="color:var(--blue)">{{ s.hum }}%</span><span class="s-lbl">Humidity</span></div>
  <div class="s-item"><span class="s-val" style="color:var(--green)">{{ s.soil }}%</span><span class="s-lbl">Soil</span></div>
</div>
<div class="s-time">Last updated: {{ s.last_update }}</div>

<!-- ESP STATUS -->
<div class="esp-bar" id="esp-bar">
  {% for key, val in esp.items() %}
  <div class="esp-item"><span class="esp-dot {{ 'online' if val == 'online' else '' }}" data-esp="{{ key }}"></span>{{ key.split('_')[0]|upper }}</div>
  {% endfor %}
</div>

<!-- ==================== PAGE 1: CONTROL ==================== -->
<div id="page-ctrl">

    <div class="section">
    <div class="section-title">WATER SOURCE</div>
    <div class="mode-row">
      <button class="mode-btn pump-btn" id="btn-pump" onclick="setMode('PUMP')">
        <span class="icon">⛽</span> POMPA
        <div class="sigorta-row" id="sigorta-row">
          <span class="sig-dot" data-sig="0"></span>
          <span class="sig-dot" data-sig="1"></span>
          <span class="sig-dot" data-sig="2"></span>
        </div>
      </button>
      <button class="mode-btn city-btn" id="btn-city" onclick="setMode('CITY')">
        <span class="icon">🏙</span> CITY WATER
      </button>
    </div>
    <button class="stop-btn" onclick="stopAll()">🛑 STOP ALL</button>
  </div>

  <div class="section">
    <div class="section-title">ZONES</div>
    <div class="zone-grid" id="zone-grid">
      {% for i in range(1, 16) %}
      {% set v = valves[i|string] %}
      <button class="zone-btn" id="zone-{{ i }}" onclick="zoneClick({{ i }})">
        {% if i <= 7 %}
        <span class="z-group">ESP2</span>
        {% elif i <= 11 %}
        <span class="z-group">ESP3</span>
        {% else %}
        <span class="z-group">ESP4</span>
        {% endif %}
        <span class="z-num">{{ i }}</span>
        <span class="z-timer">{{ v.name }}</span>
      </button>
      {% endfor %}
    </div>
  </div>
</div>

<!-- ==================== PAGE 2: SCHEDULE ==================== -->
<div id="page-sch" class="hidden">
  <div class="section">
    <div class="section-title">WEEKLY SCHEDULE</div>
    <div class="sch-list" id="sch-list"></div>

    <div class="sch-form">
      <select id="sch-day">
        <option value="Mon">Monday</option><option value="Tue">Tuesday</option>
        <option value="Wed">Wednesday</option><option value="Thu">Thursday</option>
        <option value="Fri">Friday</option><option value="Sat">Saturday</option>
        <option value="Sun">Sunday</option>
      </select>
      <input type="time" id="sch-time" value="06:00">
      <select id="sch-zone">
        {% for i in range(1, 16) %}
        <option value="{{ i }}">{{ valves[i|string].name }} ({{ i }})</option>
        {% endfor %}
      </select>
      <select id="sch-mod">
        <option value="PUMP">Pump</option>
        <option value="CITY">City Water</option>
      </select>
      <input type="number" id="sch-dur" value="30" min="1" max="240" placeholder="Duration (min)">
      <button onclick="addSchedule()">➕ ADD SCHEDULE</button>
    </div>
  </div>
</div>

<!-- TIMER MODAL -->
<div class="modal-bg" id="modal">
  <div class="modal">
    <h3 id="modal-title">Zone 1</h3>
    <p style="color:var(--muted); font-size:13px; margin-bottom:12px;">Duration (minutes)</p>
    <input class="modal-input" id="modal-mins" type="number" value="30" min="1" max="240">
    <div class="modal-btns">
      <button class="modal-btn cancel" onclick="closeModal()">Cancel</button>
      <button class="modal-btn ok" onclick="confirmZone()">Start</button>
    </div>
  </div>
</div>

<script>
let selectedZone = null;
let currentState = null;

// Clock
function updateClock() {
  const now = new Date();
  document.getElementById('clock').textContent =
    now.toLocaleTimeString('en-US', {hour:'2-digit', minute:'2-digit', second:'2-digit', timeZone:'{{ timezone }}'});
}
setInterval(updateClock, 1000);
updateClock();

// Page switching
function showPage(p) {
  document.getElementById('page-ctrl').classList.toggle('hidden', p !== 'ctrl');
  document.getElementById('page-sch').classList.toggle('hidden', p !== 'sch');
  document.getElementById('tab-ctrl').classList.toggle('active', p === 'ctrl');
  document.getElementById('tab-sch').classList.toggle('active', p === 'sch');
  if (p === 'sch') loadSchedule();
}

// API helper — no more reload, just trigger a poll
function api(url, data) {
  return fetch(url, {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify(data)
  }).then(r => r.json()).then(r => {
    // Poll quickly a few times to catch transition animations
    setTimeout(pollState, 200);
    setTimeout(pollState, 800);
    setTimeout(pollState, 2000);
    setTimeout(pollState, 4000);
    return r;
  });
}

// ─── LIVE STATE UPDATER ─────────────────────────────────
function pollState() {
  fetch('/api/state').then(r => r.json()).then(applyState).catch(() => {});
}

function applyState(data) {
  currentState = data;

  // Mode buttons
  const pumpBtn = document.getElementById('btn-pump');
  const cityBtn = document.getElementById('btn-city');
  pumpBtn.classList.toggle('active', data.mode === 'PUMP');
  cityBtn.classList.toggle('active', data.mode === 'CITY');

  // Breaker dots
  data.pump.sigorta.forEach((on, i) => {
    const dot = document.querySelector(`[data-sig="${i}"]`);
    if (dot) dot.classList.toggle('active', on);
  });

  // MQTT dot
  const mqttDot = document.querySelector('.mqtt-dot');
  if (mqttDot) mqttDot.classList.toggle('live', data.mqtt);

  // Sensors
  const svals = document.querySelectorAll('.s-val');
  if (svals.length >= 3) {
    svals[0].textContent = data.sensors.temp + '°';
    svals[1].textContent = data.sensors.hum + '%';
    svals[2].textContent = data.sensors.soil + '%';
  }
  const stime = document.querySelector('.s-time');
  if (stime) stime.textContent = 'Last updated: ' + data.sensors.last_update;

  // ESP status dots
  Object.entries(data.esp).forEach(([key, val]) => {
    const dot = document.querySelector(`[data-esp="${key}"]`);
    if (dot) dot.classList.toggle('online', val === 'online');
  });

  // Zone buttons
  for (let i = 1; i <= 15; i++) {
    const btn = document.getElementById('zone-' + i);
    if (!btn) continue;
    const v = data.valves[String(i)];
    if (!v) continue;

    btn.classList.toggle('active', v.active);
    btn.classList.toggle('closing', v.closing);

    // Badge
    let badge = btn.querySelector('.badge');
    if (v.active) {
      if (!badge) {
        badge = document.createElement('span');
        badge.className = 'badge';
        btn.insertBefore(badge, btn.firstChild);
      }
      badge.className = 'badge badge-open';
      badge.textContent = 'OPEN';
    } else if (v.closing) {
      if (!badge) {
        badge = document.createElement('span');
        badge.className = 'badge';
        btn.insertBefore(badge, btn.firstChild);
      }
      badge.className = 'badge badge-closing';
      badge.textContent = 'CLOSNG';
    } else {
      if (badge) badge.remove();
    }

    // Remaining time
    const timer = btn.querySelector('.z-timer');
    if (timer && v.end_time && v.active) {
      const end = new Date(v.end_time.replace(' ', 'T'));
      const diff = Math.max(0, Math.floor((end - new Date()) / 1000));
      const mm = Math.floor(diff / 60);
      const ss = diff % 60;
      timer.textContent = mm + ':' + String(ss).padStart(2, '0');
      timer.style.color = 'var(--green)';
    } else if (timer) {
      timer.textContent = v.name;
      timer.style.color = '';
    }
  }
}

// Poll every 1 second for responsive feel
setInterval(pollState, 1000);
pollState();

// ─── MODE CONTROL (no reload) ─────────────────────────────
function setMode(m) {
  const mode = currentState ? currentState.mode : '{{ mode }}';
  if ((m === 'PUMP' && mode === 'PUMP') || (m === 'CITY' && mode === 'CITY')) {
    api('/api/mode', {mode: 'OFF'});
    return;
  }
  if (m === 'PUMP' && mode === 'CITY') {
    if (!confirm('City water is on! It will be turned off before pump starts. Continue?')) return;
  }
  if (m === 'CITY' && mode === 'PUMP') {
    if (!confirm('Pump is on! It will be turned off before city water starts. Continue?')) return;
  }
  api('/api/mode', {mode: m});
}

function stopAll() {
  if (confirm('Are you sure you want to stop the entire system?')) {
    api('/api/stop_all', {});
  }
}

// ─── ZONE CLICK (no reload) ─────────────────────────────
function zoneClick(z) {
  if (!currentState) return;
  const v = currentState.valves[String(z)];
  if (!v) return;
  if (v.active || v.closing) {
    api('/api/valve', {zone: z, action: 'stop'});
    return;
  }
  selectedZone = z;
  document.getElementById('modal-title').textContent = v.name + ' (' + z + ')';
  document.getElementById('modal-mins').value = 30;
  document.getElementById('modal').classList.add('show');
}

function closeModal() {
  document.getElementById('modal').classList.remove('show');
  selectedZone = null;
}

function confirmZone() {
  const mins = parseInt(document.getElementById('modal-mins').value) || 30;
  api('/api/valve', {zone: selectedZone, action: 'start', duration: mins});
  closeModal();
}

// ─── SCHEDULE ───────────────────────────────────────────
function loadSchedule() {
  fetch('/api/schedule').then(r => r.json()).then(data => {
    const list = document.getElementById('sch-list');
    const dayNames = {Mon:'Mon', Tue:'Tue', Wed:'Wed', Thu:'Thu', Fri:'Fri', Sat:'Sat', Sun:'Sun'};
    if (data.schedule.length === 0) {
      list.innerHTML = '<p style="color:var(--muted);text-align:center;padding:20px;">No schedules yet</p>';
      return;
    }
    list.innerHTML = data.schedule.map((s, i) => `
      <div class="sch-card">
        <div class="sch-info">
          <span class="sch-day">${dayNames[s.day] || s.day}</span>
          <span class="sch-time">${s.time}</span>
          · Zone ${s.zone} · ${s.duration}min · ${s.mod || 'PUMP'}
        </div>
        <button class="sch-del" onclick="delSchedule(${i})">✕</button>
      </div>
    `).join('');
  });
}

function addSchedule() {
  const data = {
    day:      document.getElementById('sch-day').value,
    time:     document.getElementById('sch-time').value,
    zone:     parseInt(document.getElementById('sch-zone').value),
    mod:      document.getElementById('sch-mod').value,
    duration: parseInt(document.getElementById('sch-dur').value) || 30
  };
  api('/api/schedule/add', data).then(() => loadSchedule());
}

function delSchedule(idx) {
  api('/api/schedule/delete', {index: idx}).then(() => loadSchedule());
}
</script>
</body>
</html>
"""

# ============================================================
# 6b. FLASK ROUTES
# ============================================================

@app.route("/")
def index():
    return render_template_string(
        HTML_MAIN,
        mode=STATE["mode"],
        sig=STATE["pump"]["sigorta"],
        valves=STATE["valves"],
        s=STATE["sensors"],
        esp=STATE["esp_status"],
        mqtt_ok=STATE["mqtt_connected"],
        timezone=TIMEZONE
    )

@app.route("/api/state")
def api_state():
    return jsonify({
        "mode":    STATE["mode"],
        "pump":    STATE["pump"],
        "sebeke":  STATE["city_water"],
        "valves":  STATE["valves"],
        "sensors": STATE["sensors"],
        "esp":     STATE["esp_status"],
        "mqtt":    STATE["mqtt_connected"]
    })

@app.route("/api/mode", methods=["POST"])
def api_mode():
    data = request.get_json(force=True)
    mode = data.get("mode", "OFF")

    if mode == "PUMP":
        # SAFETY: Cannot start pump while city water active — close first
        if STATE["city_water"]["active"]:
            city_water_close()
            time.sleep(VALVE_CLOSE_DELAY)
        threading.Thread(target=pump_start, daemon=True).start()
    elif mode == "CITY":
        # SAFETY: Cannot start city water while pump active — close first
        if STATE["pump"]["active"]:
            pump_stop()
            time.sleep(VALVE_CLOSE_DELAY)
        city_water_open()
    else:
        threading.Thread(target=stop_all, daemon=True).start()
    return jsonify({"ok": True})

@app.route("/api/valve", methods=["POST"])
def api_valve():
    data = request.get_json(force=True)
    zone   = int(data.get("zone", 0))
    action = data.get("action", "start")

    if zone < 1 or zone > 15:
        return jsonify({"error": "Invalid zone"}), 400

    if action == "start":
        mins = int(data.get("duration", 30))
        end_time = now() + datetime.timedelta(minutes=mins)
        STATE["valves"][str(zone)]["end_time"] = end_time.strftime("%Y-%m-%d %H:%M:%S")
        irrigation_start(zone, STATE["mode"] if STATE["mode"] != "OFF" else "PUMP")
    else:
        irrigation_stop(zone)

    return jsonify({"ok": True})

@app.route("/api/stop_all", methods=["POST"])
def api_stop_all():
    stop_all()
    return jsonify({"ok": True})

@app.route("/api/schedule")
def api_schedule_list():
    return jsonify({"schedule": STATE["schedule"]})

@app.route("/api/schedule/add", methods=["POST"])
def api_schedule_add():
    data = request.get_json(force=True)
    entry = {
        "day":      data.get("day", "Mon"),
        "time":     data.get("time", "06:00"),
        "zone":     int(data.get("zone", 1)),
        "mod":      data.get("mod", "PUMP"),
        "duration": int(data.get("duration", 30))
    }
    STATE["schedule"].append(entry)
    save_schedule()
    return jsonify({"ok": True})

@app.route("/api/schedule/delete", methods=["POST"])
def api_schedule_delete():
    data = request.get_json(force=True)
    idx  = int(data.get("index", -1))
    if 0 <= idx < len(STATE["schedule"]):
        STATE["schedule"].pop(idx)
        save_schedule()
    return jsonify({"ok": True})

# ============================================================
# 7. START SERVER
# ============================================================
if __name__ == "__main__":
    print("\n" + "=" * 50)
    print("  REIS ORGANIC GARDEN - Irrigation Control Server")
    print("  http://0.0.0.0:5000")
    print("=" * 50 + "\n")
    app.run(host="0.0.0.0", port=5000, debug=False)

